= Project Beagle

Einfaches Tool zum Suchen von Dateien.

== Architektur

 * Spring (Boot) im Backend
 * Angular JS 1 als Frontend
 * RDBMS als konsistente Datenbasis
 * Elasticsearch zur Indizierung der PDF-Dokumente (Profile)

== Aktueller Stand

Proof-of-Concept-Phase.

== TODOs

* Durchsuche Code nach "TODO" bzw. "TODO MVR".

* link:todo.adoc[todo.adoc]

== Build

`mvn clean install`

`mvn test` (es gibt noch keine)

== Elasticsearch

Zur Indizierung der Dokumente wird Elasticsearch verwendet.
Dies muss entsprechend installiert und konfiguriert werden

- Elasticsearch 5.6.2 (6.0.0 sollte auch funktionieren)
- ingest attachment plugin : `sudo bin/elasticsearch-plugin install ingest-attachment`
- Plugin Konfiguration:

```
PUT _ingest/pipeline/attachment
{
  "description" : "Extract attachment information",
  "processors" : [
    {
      "attachment" : {
        "field" : "data",
        "indexed_chars" : -1
      }
    }
  ]
}
```

Quellen:
 * https://stackoverflow.com/questions/34857179/how-to-index-a-pdf-file-in-elasticsearch
 * https://stackoverflow.com/questions/37861279/how-to-index-a-pdf-file-in-elasticsearch-5-0-0-with-ingest-attachment-plugin?rq=1

== Ausführen

 * `java -jar target/beagle-version.jar`

 * Elastic Search (Cluster).
 Kann konfiguriert werden, siehe application.properties.
 Standard ist `http://localhost:9200`

== Lizenz

Copyright (c) 2017 Markus von Rüden

GPL v3. Siehe link:LICENSE[LICENSE].

Die verwendeten Bilder, benutzen ggf. eine andere Lizenz: link:images.adoc[images.adoc]
